# Use an official Python runtime as a base image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install additional testing libraries if needed (e.g., pytest)
# RUN pip install pytest

# Define environment variable
ENV NAME ScoreboardSync

# Set the command to run the tests
# Assuming you are using unittest and your tests are in the tests/ directory
CMD ["python", "-m", "unittest", "discover", "tests"]
